### ISSUE TITLE
cannot import name 'asPolygon' from 'shapely.geometry'

### ISSUE THREAD

**Issue by p91g** [SamComber/spacv#4]
Hi there,

I have the latest version of shapely and it doesn't seem to recognise 'asPolygon'. Has this been depreciated from shapely?

 import spacv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\x\Documents\spopt_venv\lib\site-packages\spacv\__init__.py", line 5, in <module>
    from .spacv import *
  File "C:\Users\x\Documents\spopt_venv\lib\site-packages\spacv\spacv.py", line 7, in <module>
    from .grid_builder import construct_blocks, assign_pt_to_grid
  File "C:\Users\x\Documents\spopt_venv\lib\site-packages\spacv\grid_builder.py", line 3, in <module>
    from shapely.geometry import Polygon, asPolygon
ImportError: cannot import name 'asPolygon' from 'shapely.geometry' (C:\Users\x\Documents\spopt_venv\lib\site-packages\shapely\geometry\__init__.py)

Any recommendations would be greatly appreciated :)

P

**Comment by aszani** [comment]
I encountered an error as well. If you have a solution, please let me know how you resolved it. Thank you

**Comment by arkanoid87** [comment]
~I've downloaded the PR #6 via `spacv @ git+https://github.com/dluks/spacv@master` (spacv==0.0.22) in my `requirements.txt` but I keep getting~
```python
ImportError: cannot import name 'asPolygon' from 'shapely.geometry'
```

EDIT: do `pip uninstall spacv` before reinstalling with `pip install git+https://github.com/dluks/spacv@master`
